# Generated by Django 2.0.2 on 2018-02-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('created_at',)},
        ),
    ]
